# -*- coding: utf-8 -*-
"""Conditional & Looping

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LCa-PXFxHhRdKmcEZxAH5wrxjkbOl6V6

# LATIHAN - P0W1D3AM : Conditional & Looping

**NOMOR 1**

Buatlah sebuah kondisi untuk mengecek apakah variabel `a` **lebih kecil** dari variabel `b` berdasarkan nilai dibawah ini :
* `a` = 100
* `b` = 200

Jika `True` maka tulis/cetak `a lebih kecil dari b`
"""



"""**NOMOR 2**

Buatlah sebuah kondisi untuk mengecek apakah variabel `a` **lebih besar** dari variabel `b` berdasarkan nilai dibawah ini :
* `a` = 100
* `b` = 200

Jika `True` maka tulis/cetak `a lebih besar dari b`
"""



def mengkonversi_kelvin_ke_celcius(kelvin):
  celcius = kelvin - 273
  print('hasilnya adalah :', celcius, 'C')

mengkonversi_kelvin_ke_celcius(800)

def mengkonversi_kelvin_ke_celcius(kelvin):
  celcius = kelvin + 273
  print('hasilnya adalah :', celcius, 'C')

mengkonversi_kelvin_ke_celcius(800)

def mengkonversi_suhu_ke_fahrenheit(mode, suhu):
  if mode == 'kelvin': 
    hasil = (9/5 * suhu) + 32
    print('hasil :', hasil, 'K')
  elif mode == 'celcius':
    hasil = (5/9 * suhu) - 32
    print('hasil :', hasil, 'C')
  
mengkonversi_suhu_ke_fahrenheit('celcius', 80)
mengkonversi_suhu_ke_fahrenheit('kelvin', 80)

"""**NOMOR 3**

Buatlah sebuah kondisi untuk mengecek apakah variabel `a` **tidak sama dengan**  variabel `b` berdasarkan nilai dibawah ini :
* `a` = `januari`
* `b` = `februari`

Jika `True` maka tulis/cetak `a tidak sama dengan b`

Jika `False` maka tulis/cetak `a sama dengan b`
"""



"""**NOMOR 4**

Buatlah sebuah kondisi untuk mengecek apakah variabel `a` **sama dengan**  variabel `b` berdasarkan nilai dibawah ini :
* `a` = 1000
* `b` = 1000.0

Jika `True` maka jangan menampilkan apapun

Jika `False` maka tulis/cetak `a tidak sama dengan b`
"""



"""**NOMOR 5**

Buatlah sebuah kondisi untuk mengecek apakah variabel `a` **berbeda**  variabel `b` berdasarkan nilai dibawah ini :
* `angka_ganjil` = `[1, 3, 5, 7]`
* `angka_genap`  = `[2, 4, 6, 8]`

Jika `True` maka tulis/cetak `a berbeda dengan b`

Jika `False` maka tulis/cetak `a sama dengan b`
"""



"""**NOMOR 6**

Buatlah sebuah kondisi untuk mengecek apakah variabel-variabel dibawah ini mempunyai nilai atau tidak 

* `nama` = `budi`
* `usia` = 20
* `jenis_kelamin_pria` = True
* `alamat` = `None`
* `jumlah_motor` = 0
* `punya_rumah` = `False`

Jika True maka tulis/cetak `ada`

Jika False maka tulis/cetak `tidak ada`
"""















"""**NOMOR 7**

Buatlah sebuah kondisi untuk mengecek apakah variabel-variabel dibawah ini termasuk salah satu nilai dari variabel lain atau tidak

* *`pendidikan` = `s1`* terhadap *`daftar_pendidikan` = ['s1', 's2', 's3']*
* *`nama` = `budi`* terhadap *`nama_lengkap` = `budi kurniawan`*

Jika True maka tulis/cetak `merupakan bagian`

Jika False maka tulis/cetak `bukan merupakan bagian`
"""







"""**NOMOR 8**

Buatlah sebuah kondisi untuk mengecek hubungan dua variabel dibawah ini :

* `a` = 100
* `b` = 100

Jika `a < b` maka tulis/cetak `a lebih kecil dari b`

Jika `a > b` maka tulis/cetak `a lebih besar dari b`

Selain kondisi diatas, maka tulis/cetak `a sama dengan b`
"""



"""**NOMOR 9**

Buatlah sebuah kondisi untuk memilih menu makanan dengan syarat :

* Pilih `nasi goreng` jika uang yang dimiliki lebih dari sama dengan Rp 15.000,-
* Pilih `ketoprak` jika uang yang dimiliki lebih dari sama dengan Rp 10.000 dan kurang dari Rp 15.000,-
* Pilih `batagor` jika uang yang dimiliki lebih dari sama dengan Rp 5.000 dan kurang Rp 10.000,-
* Pilih `es teh manis` jika uang yang dimiliki kurang dari Rp 5000
"""

#input

# Cara 1

# Cara 2

"""**NOMOR 10**

Buatlah sebuah perulangan untuk mencetak/menulis kata `hello` sebanyak `5` kali.
"""

# Cara 1 - Tanpa Looping

# Cara 2 - Dengan Looping (for)

# Cara 3 - Dengan Looping (while)

"""**NOMOR 11**

Buatlah sebuah perulangan untuk menampilkan angka dari `0` - `5`

*Hasil : 0, 1, 2, 3, 4, 5*
"""

# Sintaks Dasar

# Sintaks Full

# Lompatan = 2

"""**NOMOR 12**

Buatlah sebuah perulangan untuk menampilkan angka dari `3` - `5`

*Hasil : 3, 4, 5*
"""



"""**NOMOR 13**

Buatlah sebuah perulangan untuk menampilkan angka dari `1` - `10` dengan jarak angka adalah `3`

*Hasil : 1, 4, 7, 10*
"""



"""**NOMOR 14**

Buatlah sebuah perulangan untuk menampilkan angka dari `1` - `10` dan berhenti dengan kondisi jika angka tersebut adalah `8`

*Hasil : 1, 2, 3, 4, 5, 6, 7, 8*
"""



"""**NOMOR 15**

Buatlah sebuah perulangan untuk menampilkan angka genap dari `1` - `10` dan angka tersebut kurang dari sama dengan 6

*Hasil : 2, 4, 6*
"""



"""**NOMOR 16**

Buatlah sebuah perulangan untuk menampilkan isi dari variabel list dibawah ini : 

* `daftar_nama` = `['anwar', 'budi', 'cecep', 'deny']`
"""



